# -*- coding: utf-8 -*-
"""Naive_Bayes_Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JRA_ISp_rBoOrbpESLhdbGJ-xnuPKWVN

Import required Libraries
"""

from sklearn import datasets
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

"""Split data set for training, testing"""

iris_data = datasets.load_iris()
X = iris_data.data
Y = iris_data.target
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2)

"""Train model"""

gnb = GaussianNB()
Trained_model = gnb.fit(X_train, Y_train)

"""Prediction"""

Prediction = gnb.predict(X_test)
print(confusion_matrix(Y_test,Prediction))